dark mode
idea2app/idea2app.github.io pull request #64
Opened 2024-10-10 17:05 UTC by Soecka

[add] darkmode
[polish] MainNavigator, ColorModeDropdown
[config] tailwind, eslint, postcss
[migrate] replace bootstrap with material-ui within components [fix] dark mode flicker

Checklist（清单）:

- [X] Labels
- [ ] Assignees
- [X] Reviewers

- Closes #53 
- Closes #54

2024-10-14 08:09 UTC, wangrunlin approved these changes

2024-10-14 08:10 UTC, wangrunlin commented
这个 PR 内容好多，不过 Vercel 部署似乎失败了，我用在线环境看下效果。

2024-10-14 08:13 UTC, wangrunlin commented
> 这个 PR 内容好多，不过 Vercel 部署似乎失败了，我用在线环境看下效果。

确实是有问题的，直接跑 dev 跑不起来，可能整体环境还有些问题，或者需要环境变量。

2024-10-14 08:41 UTC, Soecka commented
> 这个 PR 内容好多，不过 Vercel 部署似乎失败了，我用在线环境看下效果。

是的，pnpm build 没通过，我有些 detail 页面还没改完，有报错，稍等哈~

2024-10-14 13:10 UTC, TechQuery commented on components/Member/Card.tsx
> +import { Avatar, Card, CardActions, CardContent, CardHeader, CardProps, Chip } from '@mui/material';
```suggestion
import { Markdown } from 'react-marked-renderer';
import { Avatar, Card, CardActions, CardContent, CardHeader, CardProps, Chip } from '@mui/material';

import { Member } from '../../models/Member';
```

2024-10-14 13:11 UTC, TechQuery commented on components/Member/Card.tsx
> +  ({ id, className, nickname, skill, position, summary, github, ...props }) => (
```suggestion
  ({ id, className = '', nickname, skill, position, summary, github, ...props }) => (
```

2024-10-14 13:16 UTC, TechQuery commented on models/Member.ts
> +  pageSize = 20;
```suggestion

  @observable
  accessor pageSize = 20;

```

2024-10-14 13:19 UTC, TechQuery commented on models/Repository.ts
> +  };
不是所有地方都要查嵌套数据，默认开启会导致用户浏览器在没 token 的匿名模式下很快烧干他 IP 的配额。

2024-10-14 13:22 UTC, TechQuery commented on package.json
>      "mobx-lark": "^2.0.0-rc.2",
```suggestion
    "mobx-lark": "^2.0.0-rc.3",
```

2024-10-14 13:23 UTC, TechQuery commented on package.json
>      "web-utility": "^4.4.0",
```suggestion
    "web-utility": "^4.4.1",
```

2024-10-14 13:24 UTC, TechQuery commented on package.json
> +    "@types/node": "^22.7.4",
先用 Node.js 20 (LTS)，以确保兼容性。

2024-10-14 13:28 UTC, TechQuery commented on pages/_app.tsx
> +    }
```suggestion
const container = isServer() ? null : document.getElementById('__next');

export const theme = createTheme({
  colorSchemes: { dark: true, light: true },
  /**
   * @see {@link  https://mui.com/material-ui/customization/css-theme-variables/usage/#adding-new-theme-tokens}
   * @see {@link  https://mui.com/material-ui/customization/css-theme-variables/configuration/#toggling-dark-mode-manually}
   */
  cssVariables: { colorSchemeSelector: 'class' },
  /**
   * add your custom token here, Palette, Typography, etc. @see {@link  https://mui.com/material-ui/customization/palette/} for more details
   */
  components: {
    /**
     * target root element for Portal-related elements, for tailwind support @see {@link  https://mui.com/material-ui/integrations/interoperability/#setup}
     * */
    MuiPopover: { defaultProps: { container } },
    MuiPopper: { defaultProps: { container } },
    MuiDialog: { defaultProps: { container } },
    MuiModal: { defaultProps: { container } }
```

2024-10-14 13:35 UTC, TechQuery commented on pages/member/[nickname].tsx
> +          <Tabs className="">
```suggestion
          <MemberCard className="sticky-top" style={{ top: '6.5rem' }} {...member} />
          <Tabs>
```

2024-10-14 13:35 UTC, TechQuery commented on pages/member/[nickname].tsx
> +          <div role='tabpanel'></div>
这是干嘛的？

2024-10-14 13:56 UTC, Soecka commented on pages/member/[nickname].tsx
> +          <div role='tabpanel'></div>
没写完

2024-10-14 13:57 UTC, Soecka commented on pages/member/[nickname].tsx
> +          <Tabs className="">
没写完

2024-10-14 14:18 UTC, Soecka commented on .eslintrc.json
> +          "dictionaries": ["typescript", "node", "html", "css", "bash", "npm"]
字典集合

2024-10-14 16:49 UTC, Soecka commented on components/Git/Card.tsx
> +  ({ className, full_name, html_url, languages = [], topics = [], description, homepage }) => (
为什么要加上？ Partner 那里不是不要了吗

2024-10-14 17:30 UTC, Soecka commented on components/Icon.tsx
> +    {name}
不这样写，这个不包裹任何东西，单纯 material symbol 的一层皮

2024-10-14 17:32 UTC, Soecka commented on components/Layout/ColorModeDropdown.tsx
> +  };
设成严格模式会有些边界问题，所以没改 Eslint 配置

2024-10-14 17:33 UTC, Soecka commented on components/Layout/MainNavigator.tsx
> +];
还没开发完

2024-10-14 17:39 UTC, Soecka commented on components/Layout/MainNavigator.tsx
> +            </ul>
配个 ``html-eslint`` https://html-eslint.org/docs/rules/require-li-container ?

2024-10-14 17:40 UTC, Soecka commented on components/Layout/Svg.tsx
> +    <path d="M12.5.75C6.146.75 1 5.896 1 12.25c0 5.089 3.292 9.387 7.863 10.91.575.101.79-.244.79-.546 0-.273-.014-1.178-.014-2.142-2.889.532-3.636-.704-3.866-1.35-.13-.331-.69-1.352-1.18-1.625-.402-
eslint 检查启动就好了

2024-10-14 17:41 UTC, Soecka commented on components/Layout/Svg.tsx
> +    <path d="M12.5.75C6.146.75 1 5.896 1 12.25c0 5.089 3.292 9.387 7.863 10.91.575.101.79-.244.79-.546 0-.273-.014-1.178-.014-2.142-2.889.532-3.636-.704-3.866-1.35-.13-.331-.69-1.352-1.18-1.625-.402-
Github 拼错了你没发现

2024-10-14 17:44 UTC, Soecka commented on next.config.js
奇怪的报错，尝试改了一下，后来忘记改回来了

2024-10-14 17:45 UTC, Soecka commented on tailwind.config.ts
裸跑不用写，这些是为了搭配 Mui 的 css variable ，消除 dark mode flicker 配置的

2024-10-14 17:46 UTC, Soecka commented on tsconfig.json
> +    "moduleResolution": "bundler",
之前调试 App Router 和 pigmentcss 按推荐文档的尝试

2024-10-14 17:48 UTC, Soecka commented on tsconfig.json
> +    "plugins": [{ "name": "next" }]
应该是 next 跑起来自己加的吧

2024-10-14 17:48 UTC, Soecka commented on tsconfig.json
> +    "babel.config.js"
这些都不是我改动的，next dev 自己加的

2024-10-14 17:59 UTC, Soecka commented on models/Member.ts
> +  pageSize = 20;
```
pageSize" 在类 "{ requiredKeys: readonly ("id" | "nickname" | "type" | "skill" | "position" | "summary" | "github" | "joinedAt")[]; sort: Partial<Record<"id" | "nickname" | "type" | "skill" | "position" | "summary" | "github" | "joinedAt", "ASC" | "DESC">>; ... 41 more ...; uploading: number; }" 中定义为属性，但这里在 "MemberModel" 中重写为访问器
```

2024-10-14 18:58 UTC, TechQuery commented on .eslintrc.json
> +  },
> 没搜索到相关文档，不配就会有这个报错 `23:9 Error: 'React' must be in scope when using JSX react/react-in-jsx-scope`

1. https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md#when-not-to-use-it
2. https://stackoverflow.com/a/79081395

2024-10-14 18:59 UTC, TechQuery commented on components/Git/Card.tsx
> +  ({ className, full_name, html_url, languages = [], topics = [], description, homepage }) => (
> Partner 那里不是不要了吗

“Partner 那里”是哪里？“不要了”是不要啥？

2024-10-14 19:04 UTC, TechQuery commented on components/Icon.tsx
> +    {name}
> 不这样写，这个不包裹任何东西，单纯 material symbol 的一层皮

里面的 `<span />` 都是直接把文本子节点通过 CSS 转为 Icon Font，外面通过 `children` 以同样的方式透传是很自然的。

2024-10-14 19:05 UTC, TechQuery commented on components/Layout/ColorModeDropdown.tsx
> +  };
> 边界问题

具体是指？

2024-10-14 19:11 UTC, TechQuery requested changes

2024-10-14 19:11 UTC, TechQuery commented on tailwind.config.ts
> +module.exports = {
```suggestion
export default {
```

2024-10-14 19:11 UTC, TechQuery commented on tailwind.config.ts
> +          A700: 'var(--mui-palette-grey-A700)'
既然是 JS 配置文件，类似大片有规律的配置直接用 `[].map()` 迭代出来吧。

2024-10-14 19:13 UTC, TechQuery commented on models/Repository.ts
> +  };
> SSG 缓存不消化 API，要不全部转 SSG 吧

1. 多路径配置繁琐，尤其是 i18n，因此 MobX-i18n 一开始的设计就是充分利用可变数据的响应式机制来极大简化代码。
2. `getStaticProps()` + `getStaticPaths()` 和 `getServerSideProps()` 的用法截然不同，后者除了方便用中间件处理动态内容，还能实现前者所有效果，学习、封装一种能实现所有需求，加载速度慢也可由 `cache()` 中间件解决（除了服务端内存占用大一些），综合性价比很高。

2024-10-15 09:21 UTC, Soecka commented on components/Git/Card.tsx
> +  ({ className, full_name, html_url, languages = [], topics = [], description, homepage }) => (
写太晚眼睛看花了，https://github.com/idea2app/idea2app.github.io/pull/64#discussion_r1799347950 此处我以为是删除空值

2024-10-15 09:31 UTC, Soecka commented on components/Icon.tsx
> +    {name}
这是 symbol，不是 icon font, icon font Google 那边已经废弃了

为什么要强制透传 children 呢？我只要一个 name ，children 是 ReactNode ，这是两个不同的概念

2024-10-15 09:42 UTC, Soecka commented on components/Layout/ColorModeDropdown.tsx
> +  };
https://eslint.org/docs/latest/rules/arrow-body-style
严格模式，要求单行必定返回，这意味着返回调用函数的执行，我觉得语义上有分歧，只是做一个 side effect 操作，为什么要返回执行结果

此外，如果添加内容，diff 从原本一行编程四行

2024-10-15 09:48 UTC, Soecka commented on components/Git/Logo.tsx
> +    const { name, className } = this.props;
这个我真没找到插件

2024-10-15 10:19 UTC, TechQuery commented on components/Icon.tsx
> +    {name}
> 这是 symbol，不是 icon font, icon font Google 那边已经废弃了

Symbol Icon 是一类基于新技术进行文字替换的特殊字体：
![image](https://github.com/user-attachments/assets/c2748bc5-9b45-45ed-82dd-4d3be93aa5cc)

> 为什么要强制透传 children 呢？我只要一个 name ，children 是 ReactNode ，这是两个不同的概念

`children` 只是默认类型为 `ReactNode`，具体组件可以自定义，TS 根据作者的类型定义来检查。它甚至可以是 `Function`，Ant Design 的表单组件常用这种模式。

让用户通过 `children` 传 Symbol 不但少记忆、书写一个自定义属性名，也符合 Symbol Icon 原本的生效机制 —— 应用特殊 Font 来渲染文本为图标，屏幕阅读器读到的是文本，肉眼看到的是图标。（详见上图）

2024-10-15 10:23 UTC, TechQuery commented on components/Git/Logo.tsx
> +    const { name, className } = this.props;
> 这个我真没找到插件

因为很多组件库会用 `classNames()`，我们直接用简化的模板字符串。

2024-10-15 10:59 UTC, Soecka commented on tailwind.config.ts
> +          A700: 'var(--mui-palette-grey-A700)'
你可以提 issue，我不会在这个 PR 改

2024-10-15 11:26 UTC, Soecka commented on components/Icon.tsx
> +    {name}
这点我很难 get 到，我只要一个字符串，你给出的许可是传 children，字符串是 string，children 是 ReactNode，children 集合包含 string
外面别人调用，我限定了 string，别人好理解，你给的是 children，没有限制

此外，屏幕阅读器优化不会这样做，有相关可访问性 issue，我最后会通过测试补上这块内容，加上

``aria-hidden="false" aria-label="Example home icon"``

2024-10-15 11:29 UTC, Soecka commented on components/Layout/ColorModeDropdown.tsx
> +  };
这又是一个特殊用例，Eslint 无法 100% 覆盖，但是你有强制要求，我不知道怎样处理……

2024-10-15 11:44 UTC, Soecka commented on models/Repository.ts
> +  };
总结一下今天翻到的 i18n 方案
1. wikipedia 三级域名
2. MDN 多路径
3. web.dev path 参数 ``?en``（实际生成了多个页面 ）

他们大多数都是用类似多路径的方法，而且这有一个好处，可以用 `<link hreflang='en'  href='xx' />` 关联所有语言页面，方便搜索引擎页面优化
> https://developers.google.com/search/docs/specialty/international/localized-versions

目前的渲染模式，只有首屏时间是优化了的，内容都要等待用户请求头确定，仅为这一点用 Next 框架我觉得有点买椟还珠……
之后如果 App Router 稳定了，迁移也更加方便

此外，我目前是这样区分 SSG 和 SSR的 ，如果没有用户状态或者都应该用 SSG，语言属于可以枚举的用户状态，我认为也可以用 SSG

2024-10-15 14:30 UTC, TechQuery commented on components/Icon.tsx
> +    {name}
> 外面别人调用，我限定了 string，别人好理解，你给的是 children，没有限制

你仔细看我上面的 suggestion 代码，限定了 `children: string`……

> 此外，屏幕阅读器优化不会这样做，有相关可访问性 issue，我最后会通过测试补上这块内容，加上
> 
> `aria-hidden="false" aria-label="Example home icon"`

无障碍优化的最直接方式就是纯文本，Bootstrap 官方指导的方法就是[写文本后 `visibility-hidden`][1]，Material Design 采用 Symbol Icon Font 机制恰恰是把这种方法简化到极致。Emoji 的多字符合成单个复杂字符就是这个机制，如三个单人 emoji 合成一个三人 emoji。

[1]: https://getbootstrap.com/docs/5.3/getting-started/accessibility/#visually-hidden-content

2024-10-15 14:33 UTC, TechQuery commented on components/Icon.tsx
> +    {name}
> 其次，开发者用 icon ，他的流程也是去官网搜索，然后点击 copy icon name

copy 的是 name，不是完整代码啊，还得包装，只是哪种更易用：

```tsx
<Icon name="icon-name" />
// or
<Icon>icon-name</Icon>
```

2024-10-15 14:44 UTC, Soecka commented on components/Icon.tsx
> +    {name}
1. 你推崇的 [MDUI Icon](https://www.mdui.org/en/docs/2/components/icon) 的写法

``<mdui-icon name="search"></mdui-icon>``

2. [Angular](https://material.angular.io/components/icon/examples) 写法

``<mat-icon aria-hidden="false" aria-label="Example home icon" fontIcon="home"></mat-icon>``

这两种写法差异这么大吗？info warnning error fatal 你给哪一档?
children 想当然是 ReactNode，这种默认写法，开发者直接复制 insert the icon 那一列？

2024-10-15 14:51 UTC, Soecka commented on components/Icon.tsx
> +    {name}
或者全都不要，总共五六个，我梭哈 SVG 了……

2024-10-15 15:05 UTC, TechQuery commented on models/Repository.ts
> +  };
> 他们大多数都是用类似多路径的方法，而且这有一个好处，可以用 `<link hreflang='en' href='xx' />` 关联所有语言页面，方便搜索引擎页面优化

单路径 i18n 在服务端渲染阶段已经得知用户语言，输出 HTML 时用 JSX 设置 `hreflang` 也是易如反掌啊，`href` 就是一个固定值。

> 目前的渲染模式，只有首屏时间是优化了的，内容都要等待用户请求头确定

HTTP 请求头是 `index.html` 这第一个请求后端最早接收到的数据，何来“首屏后再等待”？这时首屏还没生成响应呢。

> 仅为这一点用 Next 框架我觉得有点买椟还珠…… 之后如果 App Router 稳定了，迁移也更加方便

App Router 不限定单/多路径啊，路径都是一个个目录和文件写出来的，服务端预加载语言、客户端切换语言本质都是基于 HTTP、Web API 标准实现的。

> 此外，我目前是这样区分 SSG 和 SSR的 ，如果没有用户状态或者都应该用 SSG，语言属于可以枚举的用户状态，我认为也可以用 SSG

用多路径做 i18n 当然可以 SSG：
1. 但可枚举的几种语言名终究很有限，用户拼接 `/unsupported-language/page/path` 就会 404，切回默认语言页面还得配后端服务器 redirect 规则。MobX-i18n 路径唯一，自动回退默认语言。
2. 多路径要多加一级路径，所有页面内 `href="/path/to/page"` 属性都失效，要么都用框架的 `<Link />`（很多组件库封装的 `<a />` 无法被替换），要么打包器配一堆插件在编译阶段魔改（也很难覆盖所有组件库的 URL 属性名）。

因此，在开源社官网做 i18n 时，基于上述考量，再看了 `react-i18n`、`next-i18n` 等库一大坨复杂的配置和 API，果断放弃，才自研了 MobX-i18n。

2024-10-15 15:19 UTC, Soecka commented on components/Layout/ColorModeDropdown.tsx
> +  };
我也不喜欢用 hook

review 是一种互动？前期 argue，慢慢趋近统一成可以表述的团队代码风格。如果之后你一直提，我一直 pass ，我觉得对双方都不是一种促进的互动。

此外，如果换个新人，再 argue 一遍，也是重复且消耗的事情。代码风格算一种最大公约数？囊括 `warning error fatal` 这些选项，`info` 如果能用插件规则囊括进去格式化，也是无关痛痒的事情，其他的我觉得可以自由发挥

2024-10-15 15:24 UTC, TechQuery requested changes

2024-10-15 15:24 UTC, TechQuery commented on components/Member/Card.tsx
> -            loading="lazy"
不在首屏的图片还是保留懒加载

2024-10-15 15:24 UTC, TechQuery commented on components/NotFoundCard.tsx
> +      //@ts-ignore
没必要变更

2024-10-15 15:24 UTC, TechQuery commented on models/Repository.ts
> +      RepositoryModel.prototype.loadPage.call(this, page, pageSize, filter);
为啥写成更麻烦的形式？

2024-10-15 15:24 UTC, TechQuery commented on next.config.mjs
>    },
```suggestion
  images: { remotePatterns: [{ protocol: 'https', hostname: 'github.com' }] },
```
不懂就问：这是设置啥的？

2024-10-15 15:24 UTC, TechQuery commented on pages/index.tsx
> +    new GitRepositoryModel('idea2app').getList({ relation: [] }, 1, 9),
无需变更

2024-10-15 15:24 UTC, TechQuery commented on tsconfig.json
> +    "moduleResolution": "node",
无需变更

2024-10-15 15:24 UTC, TechQuery commented on pages/api/GitHub/core.ts
> +      //@ts-ignore
无需变更

2024-10-15 15:34 UTC, Soecka commented on models/Repository.ts
> +      RepositoryModel.prototype.loadPage.call(this, page, pageSize, filter);
类型报错

2024-10-15 15:35 UTC, Soecka commented on next.config.mjs
>    },
next Image 不配置这个会报错，可能是为了安全

2024-10-15 15:35 UTC, Soecka commented on pages/index.tsx
> +    new GitRepositoryModel('idea2app').getList({ relation: [] }, 1, 9),
类型报错

2024-10-15 15:35 UTC, TechQuery commented on components/Icon.tsx
> +    {name}
> 1. 你推崇的 [MDUI Icon](https://www.mdui.org/en/docs/2/components/icon) 的写法
> 
> `<mdui-icon name="search"></mdui-icon>`

别人写的库我推荐只是综合考量选其中最优的，不代表每个写法我都赞成，只有我写的库才完全是我的观点。
 
> 2. [Angular](https://material.angular.io/components/icon/examples) 写法
> 
> `<mat-icon aria-hidden="false" aria-label="Example home icon" fontIcon="home"></mat-icon>`

很符合 Angular 啥都繁琐的风格……

> 这两种写法差异这么大吗？info warnning error fatal 你给哪一档?

我再次重申 —— review comment 全是建议，重点不在于采用谁的写法，而在于交流过程中的学习、提升。一个点大不大不在于涉及的代码行数或是否出错，而在于从中发散的知识树。（比如大多数人都在用 CSS icon font 传属性，Material Design 就设计出了 Symbol 文本变图标一箭双雕）

2024-10-15 15:42 UTC, TechQuery commented on components/Layout/ColorModeDropdown.tsx
> +  };
> review 是一种互动？前期 argue，慢慢趋近统一成可以表述的团队代码风格。

对，GitHub flow 就是提倡开源程序员用这种方式来协作。

> 如果之后你一直提，我一直 pass ，我觉得对双方都不是一种促进的互动。

有 Lint 规则就用，没有我尽量抑制我的处女座冲动，再有同类的你点 reaction 否决即可。

> 此外，如果换个新人，再 argue 一遍，也是重复且消耗的事情。代码风格算一种最大公约数？囊括 `warning error fatal` 这些选项，`info` 如果能用插件规则囊括进去格式化，也是无关痛痒的事情，其他的我觉得可以自由发挥

感谢你主导 ESLint 规则的收集整理，实质推动了很早提出的计划。♥

2024-10-15 15:43 UTC, TechQuery commented on pages/index.tsx
> +    new GitRepositoryModel('idea2app').getList({ relation: [] }, 1, 9),
> 类型报错

具体啥错？以前咋没有

2024-10-15 15:43 UTC, TechQuery commented on models/Repository.ts
> +      RepositoryModel.prototype.loadPage.call(this, page, pageSize, filter);
> 类型报错

具体报错贴一下

2024-10-15 16:01 UTC, Soecka commented on pages/index.tsx
> +    new GitRepositoryModel('idea2app').getList({ relation: [] }, 1, 9),
以前配置的不严格，限制的插件规则更严格一些，next 关于插件配置文档不够清晰，他都是推荐用自己的
我翻插件官方文档配的https://typescript-eslint.io/getting-started/legacy-eslint-setup#additional-configs
我把这两行删了吧
```json
'eslint:recommended',
-'plugin:@typescript-eslint/strict',
-'plugin:@typescript-eslint/stylistic',
```

2024-10-15 16:05 UTC, Soecka commented on pages/index.tsx
> +    new GitRepositoryModel('idea2app').getList({ relation: [] }, 1, 9),
```类型“{}”的参数不能赋给类型“RepositoryFilter”的参数。
  类型 "{}" 中缺少属性 "relation"，但类型 "RepositoryFilter" 中需要该属性。ts(2345)```

2024-10-15 16:11 UTC, Soecka commented on components/Layout/MainNavigator.tsx
> +            </ul>
只支持 JavaScript ，可惜了……

2024-10-15 16:15 UTC, Soecka commented on models/Repository.ts
> +  };
> 单路径 i18n 在服务端渲染阶段已经得知用户语言，输出 HTML 时用 JSX 设置 hreflang 也是易如反掌啊，href 就是一个固定值。
这个是需要一个列表，
![image](https://github.com/user-attachments/assets/0c09a3a6-c22c-4d27-b3d8-a215dd03276a)

2024-10-15 16:19 UTC, Soecka commented on components/Member/Card.tsx
> -            loading="lazy"
`Image` 组件自己有优化

2024-10-15 16:31 UTC, Soecka commented on models/Repository.ts
> +  };
> HTTP 请求头是 index.html 这第一个请求后端最早接收到的数据，何来“首屏后再等待”？这时首屏还没生成响应呢。

我的意思是只有首屏优化，把 SSG 的 SEO 放弃了

> App Router 不限定单/多路径啊，路径都是一个个目录和文件写出来的，服务端预加载语言、客户端切换语言本质都是基于 HTTP、Web API 标准实现的。
现在做 SSG ，之后迁移到 App Router 的 server component 会很丝滑，App Router 中 mobx 基本上只能在客户端组件用

我也认为 mobx-i18n 是很好的自研开源项目，很清晰

2024-10-15 17:16 UTC, TechQuery commented on models/Repository.ts
> +  };
> 我的意思是只有首屏优化，把 SSG 的 SEO 放弃了

并不只是首屏啊，SSG 和 SSR 只是服务端的不同实现方式，对一个 HTTP 客户端（浏览器、搜索引擎爬虫等）是透明的，都是发一个请求就响应一段 HTML 代码，它并不知道服务器上是一堆预编译的静态文件还是动态生成的，它也不需要知道。只要这些 HTML 是符合语义化规范的，都不影响 SEO。

2024-10-15 17:34 UTC, TechQuery commented on pages/index.tsx
> +    new GitRepositoryModel('idea2app').getList({ relation: [] }, 1, 9),
> ```
> 类型“{}”的参数不能赋给类型“RepositoryFilter”的参数。
>   类型 "{}" 中缺少属性 "relation"，但类型 "RepositoryFilter" 中需要该属性。ts(2345)
> ```

把上游库字段改成可选的就行了：https://github.com/idea2app/MobX-GitHub/blob/6cc83bcee84023d2116729b49e5b11fb1e5c8cbe/source/Repository.ts#L29-L31

2024-10-15 19:49 UTC, TechQuery requested changes

2024-10-15 19:49 UTC, TechQuery commented on pages/member/index.tsx
> +  return { props: { list: JSON.parse(JSON.stringify({ list })) as Member[] } };
```suggestion
  return { props: { list: JSON.parse(JSON.stringify(list)) as Member[] } };
```

2024-10-15 19:49 UTC, TechQuery commented on pages/project/index.tsx
> +  };
```suggestion
  return { props: { list: JSON.parse(JSON.stringify(list)) as Project[] } };
```

2024-10-15 20:06 UTC, TechQuery commented on models/Repository.ts
> +  };
> （你不能指望爬虫每天换着 cookie 来聊骚吧，那为什么要 hreflang 这些属性帮助爬虫建立多语种索引？）。

搜索引擎爬虫多语种 `Accept-Language` 头的轮询频率，我没调查过。

> 如果 SSR SEO 效果大于 SSG，那为什么不干脆全梭哈 SSR

我没说过”SSR SEO 效果大于 SSG“，我说的是”SEO 能实现“。

> 为什么 App router 中完全抛弃 getServeSIdeProops 这些 hooks?

抛弃 API 是因为 RSC 能一次性实现 SSR、SSG，不是抛弃了 SSR。App Router 其实是 Next.js ISR（SSR + SSG）模式的重新实现，让 Next.js 来掌控静态、动态的切换。

> SSR 和 SSG 也有区分（请求数据是否缓存），默认 data 都是缓存的， nextjs 15 又更改为默认不缓存

我写的 Next-SSR-middleware 中的 `cache()` 中间件就是交给开发者控制缓存的。

> 如果你认为 Mobx + App Router 可以很好的工作，不用所有地方都加 'use client' ，那你可以帮忙回答一下这个问题
> 
> [mobxjs/mobx#3805 (comment)](https://github.com/mobxjs/mobx/discussions/3805#discussioncomment-9321899)
> 
> 我目前几次尝试都以不加 ‘use client’ , mobx 依赖包需要借助 react hook 实现之类的的报错结束

我说的是：

```tsx
'use server';
import { UserModel } from '../model';

export async SSRorSSG() {
    const { name } = await new UserModel().getOne('some_uid');

    return <h1>{name}</h1>;
}
```

2024-10-16 03:07 UTC, Soecka commented on models/Repository.ts
> +  };
> 我说的是：

不继承 LIstModel 或 BaseModel 吗？继承了一样用不了……

2024-10-16 05:13 UTC, TechQuery commented on models/Repository.ts
> +  };
> 不继承 ListModel 或 BaseModel 吗？继承了一样用不了……

当然继承啊，我只当个普通的 class SDK 用，又不用响应式数据，为何不行？

2024-10-16 09:10 UTC, TechQuery requested changes

2024-10-16 09:10 UTC, TechQuery commented on babel.config.js
> +export default {
去确认一下 Babel 对 ESM 的支持是不是一定要 `.mjs` 扩展名：

![Screenshot_2024-10-16-17-07-29-670_com.android.chrome.jpg](https://github.com/user-attachments/assets/34e2bd15-1cef-4880-aaaf-2c4e3b47c318)

2024-10-16 10:12 UTC, merged